### ISSUE TITLE
os/user.Current() not supported on linux/amd64

### ISSUE THREAD

**Issue by DanielHeath** [jtolio/lecat#4]
This panics at startup:
panic: user: Current not implemented on linux/amd64
Could you use `ENV["HOME"]` instead?

**Comment by jtolio** [comment]
i've only tested this on linux/amd64. is it not being supported a new thing?

**Comment by DanielHeath** [comment]
According to https://tip.golang.org/doc/go1.7 `user.Current` requires cgo in versions prior to 1.7 which explains why I was seeing this.

**Comment by jtolio** [comment]
ah ha! okay. alright, i feel way better knowing what was up.
